name: message send

on:
  schedule:
    - cron:  "10 30 * * *"

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: "3.8"
        architecture: "x64"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run script
      env:
        TARGET_REPO_NAME: ${{ secrets.RP }}
        DISCORD_WEBHOOK_URL: ${{ secrets.WH_URL }}
      run: |
        git clone https://github.com/floorp-projects/l10n-central
        ./mach bootstrap
        echo -e "ac_add_options --with-app-name=floorp\\nac_add_options --with-app-basename=Floorp\\nac_add_options --with-branding=browser/branding/official\\nac_add_options --disable-crashreporter\\nac_add_options --enable-proxy-bypass-protection\\nac_add_options --disable-verify-mar\\nac_add_options --enable-update-channel=release\\nMOZ_REQUIRE_SIGNING=\\nMOZ_DATA_REPORTING=\\nMOZ_TELEMETRY_REPORTING=\\nac_add_options --with-mozilla-api-keyfile=/home/runner/work/Floorp/Floorp/apis/api-mozilla-key\\nac_add_options --with-google-location-service-api-keyfile=/home/runner/work/Floorp/Floorp/apis/api-google-location-service-key\\nac_add_options --with-google-safebrowsing-api-keyfile=/home/runner/work/Floorp/Floorp/apis/api-google-safe-browsing-key\\nac_add_options --enable-bootstrap\\nac_add_options --with-l10n-base=/home/runner/work/Floorp/Floorp/l10n-central/l10n-central" >> mozconfig
        ./mach configure
